OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: ""

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

PDF_STYLE:
  font_name: "SimSun"
  space: 20
  grid_color: "black"
  space_before: 5
  space_after: 5
  text_style:
    leading: 15
  table_style:
    head_background_color: "grey"
    head_text_color: "whitesmoke"
    body_background_color: "beige"





