OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "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"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

Writer:
  file_name: "test.pdf"
  file_format: "markdown"

